services:
  backend:
    build:
      context: ./backend/laravel
    container_name: backend_app
    working_dir: /var/www/laravel
    volumes:
      - ./backend/laravel:/var/www/laravel
    ports:
      - "8000:8000"
    environment:
      - REDIS_HOST=redis
      - CACHE_STORE=redis
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=swapi
      - DB_USERNAME=user
      - DB_PASSWORD=password
    depends_on:
      - redis
      - db
    command: bash -c "composer install && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=8000"

  queue:
    build:
      context: ./backend/laravel
    container_name: queue_worker
    working_dir: /var/www/laravel
    volumes:
      - ./backend/laravel:/var/www/laravel
    environment:
      - REDIS_HOST=redis
      - CACHE_STORE=redis
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=swapi
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - QUEUE_CONNECTION=database
    depends_on:
      - backend
      - db
      - redis
    command: php artisan queue:work --tries=3 --timeout=90

  scheduler:
    build:
      context: ./backend/laravel
    container_name: scheduler
    working_dir: /var/www/laravel
    volumes:
      - ./backend/laravel:/var/www/laravel
    environment:
      - REDIS_HOST=redis
      - CACHE_STORE=redis
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=swapi
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - QUEUE_CONNECTION=database
    depends_on:
      - backend
      - db
      - redis
    command: php artisan schedule:work

  frontend:
    build:
      context: ./frontend/swstarterapp
    container_name: frontend_app
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  storybook:
    build:
      context: ./frontend/swstarterapp
    container_name: storybook_app
    working_dir: /app
    ports:
      - "6006:6006"
    command: npm run storybook -- --ci --host 0.0.0.0 --port 6006
    volumes:
      - ./frontend/swstarterapp:/app
      - /app/node_modules

  redis:
    image: redis:alpine
    container_name: redis_app
    ports:
      - "6379:6379"

  db:
    image: postgres:15-alpine
    container_name: postgres_app
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: swapi
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
