services:
  backend:
    build:
      context: ./backend/laravel
    container_name: backend_app
    working_dir: /var/www/laravel
    volumes:
      - ./backend/laravel:/var/www/laravel
    ports:
      - "8000:8000"
    command: bash -c "composer install && php artisan serve --host=0.0.0.0 --port=8000"

  frontend:
    build:
      context: ./frontend/swstarterapp
    container_name: frontend_app
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - backend
